#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     INSTALAR FERRAMENTAS     \E[0m"
    echo ""
    echo -ne "\n\033[1;32mINFORME O TOKEN\033[1;37m: "
    read token
    clear
    echo ""
    echo -e "\033[1;32mBAIXANDO... \033[0m\n"
    cd $dev/null
    rm -rf $dev/mtuning
    wget https://github.com/BGXSJYRABJE/hdisbsi/raw/main/Modulos/mtuning >/dev/null 2>&1
    chmod 777 mtuning
    echo "OK!"
    sleep 1
    mtuning
    clear
    menu
}
